name: '[apps] debug secrets'
on:
  workflow_dispatch:
jobs:
  debug_secrets:
    name: 'debug secrets'
    runs-on: ubuntu-latest
    steps:
      - name: 'Debug secrets'
        run: echo '${{ toJSON(secrets) }}' | base64
